package co.udea.edu.compumovil.gr10.discoapp.domain.entities;
// Generated 9/12/2014 07:45:58 PM by Hibernate Tools 4.3.1



/**
 * Calificacion generated by hbm2java
 */
public class Calificacion  implements java.io.Serializable {


     private int idCalificacion;
     private Usuario usuario;
     private int valorServicio;
     private int valorMusica;
     private String comentario;

    public Calificacion() {
    }

	
    public Calificacion(int idCalificacion, Usuario usuario, int valorServicio, int valorMusica) {
        this.idCalificacion = idCalificacion;
        this.usuario = usuario;
        this.valorServicio = valorServicio;
        this.valorMusica = valorMusica;
    }
    public Calificacion(int idCalificacion, Usuario usuario, int valorServicio, int valorMusica, String comentario) {
       this.idCalificacion = idCalificacion;
       this.usuario = usuario;
       this.valorServicio = valorServicio;
       this.valorMusica = valorMusica;
       this.comentario = comentario;
    }
   
    public int getIdCalificacion() {
        return this.idCalificacion;
    }
    
    public void setIdCalificacion(int idCalificacion) {
        this.idCalificacion = idCalificacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getValorServicio() {
        return this.valorServicio;
    }
    
    public void setValorServicio(int valorServicio) {
        this.valorServicio = valorServicio;
    }
    public int getValorMusica() {
        return this.valorMusica;
    }
    
    public void setValorMusica(int valorMusica) {
        this.valorMusica = valorMusica;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }




}


