package co.udea.edu.compumovil.gr10.discoapp.domain.entities;
// Generated 9/12/2014 07:45:58 PM by Hibernate Tools 4.3.1



/**
 * Cancion generated by hbm2java
 */
public class Cancion  implements java.io.Serializable {


     private int idCancion;
     private String nombre;
     private String artista;
     private String genero;

    public Cancion() {
    }

	
    public Cancion(int idCancion, String nombre) {
        this.idCancion = idCancion;
        this.nombre = nombre;
    }
    public Cancion(int idCancion, String nombre, String artista, String genero) {
       this.idCancion = idCancion;
       this.nombre = nombre;
       this.artista = artista;
       this.genero = genero;
    }
   
    public int getIdCancion() {
        return this.idCancion;
    }
    
    public void setIdCancion(int idCancion) {
        this.idCancion = idCancion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getArtista() {
        return this.artista;
    }
    
    public void setArtista(String artista) {
        this.artista = artista;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }




}


