package co.udea.edu.compumovil.gr10.discoapp.domain.entities;
// Generated 9/12/2014 07:45:58 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private int idEvento;
     private Usuario usuario;
     private String nombreEvento;
     private String descripcion;
     private Date fechaEvento;
     private String urlImagen;

    public Evento() {
    }

	
    public Evento(int idEvento, Usuario usuario, String nombreEvento, Date fechaEvento, String urlImagen) {
        this.idEvento = idEvento;
        this.usuario = usuario;
        this.nombreEvento = nombreEvento;
        this.fechaEvento = fechaEvento;
        this.urlImagen = urlImagen;
    }
    public Evento(int idEvento, Usuario usuario, String nombreEvento, String descripcion, Date fechaEvento, String urlImagen) {
       this.idEvento = idEvento;
       this.usuario = usuario;
       this.nombreEvento = nombreEvento;
       this.descripcion = descripcion;
       this.fechaEvento = fechaEvento;
       this.urlImagen = urlImagen;
    }
   
    public int getIdEvento() {
        return this.idEvento;
    }
    
    public void setIdEvento(int idEvento) {
        this.idEvento = idEvento;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreEvento() {
        return this.nombreEvento;
    }
    
    public void setNombreEvento(String nombreEvento) {
        this.nombreEvento = nombreEvento;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaEvento() {
        return this.fechaEvento;
    }
    
    public void setFechaEvento(Date fechaEvento) {
        this.fechaEvento = fechaEvento;
    }
    public String getUrlImagen() {
        return this.urlImagen;
    }
    
    public void setUrlImagen(String urlImagen) {
        this.urlImagen = urlImagen;
    }




}


