package co.udea.edu.compumovil.gr10.discoapp.domain.entities;
// Generated 9/12/2014 07:45:58 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;




/**
 * SolicitudCancion generated by hbm2java
 */
@XmlRootElement
public class SolicitudCancion  implements java.io.Serializable {


     private Integer idPeticionCancion;
     private Usuario usuario;
     private String nombrePeticion;
     private String estadoPeticion;
     private Date fechaPeticion;

    public Date getFechaPeticion() {
        return fechaPeticion;
    }

    public void setFechaPeticion(Date fechaPeticion) {
        this.fechaPeticion = fechaPeticion;
    }

    public SolicitudCancion(Usuario usuario, String nombrePeticion, String estadoPeticion, Date fechaSolicitud) {
        this.idPeticionCancion = idPeticionCancion;
        this.usuario = usuario;
        this.nombrePeticion = nombrePeticion;
        this.estadoPeticion = estadoPeticion;
        this.fechaPeticion = fechaSolicitud;
    }

    public SolicitudCancion() {
    }

    public SolicitudCancion(Usuario usuario, String nombrePeticion, String estadoPeticion) {
       this.usuario = usuario;
       this.nombrePeticion = nombrePeticion;
       this.estadoPeticion = estadoPeticion;
    }
   
    public Integer getIdPeticionCancion() {
        return this.idPeticionCancion;
    }
    
    public void setIdPeticionCancion(Integer idPeticionCancion) {
        this.idPeticionCancion = idPeticionCancion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombrePeticion() {
        return this.nombrePeticion;
    }
    
    public void setNombrePeticion(String nombrePeticion) {
        this.nombrePeticion = nombrePeticion;
    }
    public String getEstadoPeticion() {
        return this.estadoPeticion;
    }
    
    public void setEstadoPeticion(String estadoPeticion) {
        this.estadoPeticion = estadoPeticion;
    }




}


