package co.udea.edu.compumovil.gr10.discoapp.domain.entities;
// Generated 9/12/2014 07:45:58 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Usuario generated by hbm2java
 */
@XmlRootElement
public class Usuario  implements java.io.Serializable {


     private String idUsuario;
     private String password;
     private String nombreUsuario;
     private String tipoUsuario;
     private Date fechaRegistro;
     private String correoElectronico;


    public Usuario() {
    }

	
    public Usuario(String idUsuario, String password, String nombreUsuario, String tipoUsuario, Date fechaRegistro, String correoElectronico) {
        this.idUsuario = idUsuario;
        this.password = password;
        this.nombreUsuario = nombreUsuario;
        this.tipoUsuario = tipoUsuario;
        this.fechaRegistro = fechaRegistro;
        this.correoElectronico = correoElectronico;
    }
  
   
    public String getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(String idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
   




}


